<a href="https://colab.research.google.com/github/Pranaybannu/Goibibo-Hotel-Recommendations/blob/main/HotelRecommendations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/M7/goibibo_com-travel_sample.csv")

In [ ]:
data.head()

                                     additional_info  ...                           uniq_id
0  Room Service|Internet Access|Restaurant|Free I...  ...  2c8db027d43a9452a43e88eb30d9f983
1                               Room Service|Gym/Spa  ...  e98f69f889c0235e6dc480e7df6de0de
2                           Restaurant|Swimming Pool  ...  9b59d00eaffc273d83000ed7dcda0e83
3                                                NaN  ...  df0971f9c5501af112485ee28b468ce5
4                         Internet Access|Restaurant  ...  0c3514344c9cda8718f558e84bdb44ef

[5 rows x 36 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   additional_info           3192 non-null   object
 1   address                   4000 non-null   object
 2   area                      3965 non-null   object
 3   city                      4000 non-null   object
 4   country                   4000 non-null   object
 5   crawl_date                4000 non-null   object
 6   guest_recommendation      2416 non-null   float64
 7   hotel_brand               389 non-null    object
 8   hotel_category            4000 non-null   object
 9   hotel_description         3983 non-null   object
 10  hotel_facilities          3806 non-null   object
 11  hotel_star_rating         4000 non-null   int64
 12  image_count               4000 non-null   int64
 13  latitude                  4000 non-null   float64
 14  locality                  3965 non-null   object
 15  longitude                 4000 non-null   float64
 16  pageurl                   4000 non-null   object
 17  point_of_interest         3760 non-null   object
 18  property_id               4000 non-null   object
 19  property_name             4000 non-null   object
 20  property_type             4000 non-null   object
 21  province                  4000 non-null   object
 22  qts                       2716 non-null   object
 23  query_time_stamp          4000 non-null   object
 24  review_count_by_category  2415 non-null   object
 25  room_area                 1128 non-null   object
 26  room_count                4000 non-null   int64
 27  room_facilities           3730 non-null   object
 28  room_type                 4000 non-null   object
 29  similar_hotel             3917 non-null   object
 30  site_review_count         2416 non-null   float64
 31  site_review_rating        2416 non-null   float64
 32  site_stay_review_rating   4000 non-null   object
 33  sitename                  4000 non-null   object
 34  state                     4000 non-null   object
 35  uniq_id                   4000 non-null   object
dtypes: float64(5), int64(3), object(28)
memory usage: 1.1+ MB

In [ ]:
data.drop(['similar_hotel','site_review_count','site_review_rating','site_stay_review_rating','sitename','state',
'qts','query_time_stamp','review_count_by_category','room_area','room_count','image_count','latitude','longitude','pageurl',
'area','country','crawl_date','guest_recommendation','hotel_brand','locality','property_id','province'],axis=1,inplace=True)

In [ ]:
data.head()

                                     additional_info  ...                           uniq_id
0  Room Service|Internet Access|Restaurant|Free I...  ...  2c8db027d43a9452a43e88eb30d9f983
1                               Room Service|Gym/Spa  ...  e98f69f889c0235e6dc480e7df6de0de
2                           Restaurant|Swimming Pool  ...  9b59d00eaffc273d83000ed7dcda0e83
3                                                NaN  ...  df0971f9c5501af112485ee28b468ce5
4                         Internet Access|Restaurant  ...  0c3514344c9cda8718f558e84bdb44ef

[5 rows x 13 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   additional_info    3192 non-null   object
 1   address            4000 non-null   object
 2   city               4000 non-null   object
 3   hotel_category     4000 non-null   object
 4   hotel_description  3983 non-null   object
 5   hotel_facilities   3806 non-null   object
 6   hotel_star_rating  4000 non-null   int64
 7   point_of_interest  3760 non-null   object
 8   property_name      4000 non-null   object
 9   property_type      4000 non-null   object
 10  room_facilities    3730 non-null   object
 11  room_type          4000 non-null   object
 12  uniq_id            4000 non-null   object
dtypes: int64(1), object(12)
memory usage: 406.4+ KB

In [ ]:
data['additional_info'] = data['additional_info'].fillna("not available")
data['hotel_description'] = data['hotel_description'].fillna("not available")
data['hotel_facilities'] = data['hotel_facilities'].fillna("not available")
data['point_of_interest'] = data['point_of_interest'].fillna("details Unavailable")
data['room_facilities'] = data['room_facilities'].fillna("details unavailable")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   additional_info    4000 non-null   object
 1   address            4000 non-null   object
 2   city               4000 non-null   object
 3   hotel_category     4000 non-null   object
 4   hotel_description  4000 non-null   object
 5   hotel_facilities   4000 non-null   object
 6   hotel_star_rating  4000 non-null   int64
 7   point_of_interest  4000 non-null   object
 8   property_name      4000 non-null   object
 9   property_type      4000 non-null   object
 10  room_facilities    4000 non-null   object
 11  room_type          4000 non-null   object
 12  uniq_id            4000 non-null   object
dtypes: int64(1), object(12)
memory usage: 406.4+ KB

In [ ]:
data.describe(include='object')

       additional_info  ...                           uniq_id
count             4000  ...                              4000
unique              58  ...                              4000
top       Room Service  ...  7d5d78e2c8cbcec3d465c335188d8dae
freq               828  ...                                 1

[4 rows x 12 columns]

In [ ]:
data['hotel_star_rating'].value_counts()

hotel_star_rating
0    1936
3     829
2     479
1     442
4     233
5      81
Name: count, dtype: int64

In [ ]:
data['hotel_category'].value_counts()

hotel_category
regular    3871
gostays     129
Name: count, dtype: int64

In [ ]:
data['property_type'].value_counts()

property_type
Hotel                2314
Resort                516
Guest House           243
Homestay              231
Service Apartment     183
Lodge                 117
Houseboat              78
Cottage                75
Tent                   57
Villa                  49
BnB                    49
Bungalow               46
Palace                 11
Hostel                 10
Motel                   9
Farm Stay               7
Luxury Yacht            3
Beach Hut               2
Name: count, dtype: int64

In [ ]:
room_types =list(data['room_type'].value_counts().head(20).reset_index().values[:,0])

In [ ]:
room_types

['Deluxe Room',
 'Standard Room',
 'Deluxe',
 'Executive Room',
 'Super Deluxe Room',
 'Superior Room',
 'Standard',
 'AC Room',
 'Suite Room',
 'STANDARD ROOM',
 'Deluxe room',
 'Premium Room',
 'Deluxe AC Room',
 'Ac Room',
 'Luxury Room',
 'Standard room',
 'Double Room',
 'DELUXE ROOM',
 'Deluxe Rooms',
 'standard room']

In [ ]:
cond = data['room_type'].isin(room_types)
data = data[cond]

In [ ]:
data.shape

(1792, 13)

In [ ]:
data['room_type'] = data['room_type'].str.lower().str.strip()

In [ ]:
# mapping dictionary
room_mapping = {

    # STANDARD
    'standard room': 'Standard',
    'standard': 'Standard',
    'ac room': 'Standard',
    'double room': 'Standard',

    # DELUXE
    'deluxe room': 'Deluxe',
    'deluxe': 'Deluxe',
    'super deluxe room': 'Deluxe',
    'deluxe ac room': 'Deluxe',
    'deluxe rooms': 'Deluxe',

    # SUPERIOR
    'superior room': 'Superior',

    # EXECUTIVE
    'executive room': 'Executive',

    # SUITE
    'suite room': 'Suite',

    # LUXURY
    'premium room': 'Luxury',
    'luxury room': 'Luxury'
}

# apply mapping
data['room_type_cleaned'] = data['room_type'].map(room_mapping)

In [ ]:
data.head()

                                      additional_info  ... room_type_cleaned
0   Room Service|Internet Access|Restaurant|Free I...  ...            Deluxe
2                            Restaurant|Swimming Pool  ...          Standard
3                                       not available  ...            Deluxe
9                                       not available  ...            Deluxe
11         Room Service|Internet Access|Free Internet  ...            Deluxe

[5 rows x 14 columns]

In [ ]:
data['room_type_cleaned'].value_counts()

room_type_cleaned
Deluxe       973
Standard     590
Executive     90
Luxury        59
Superior      44
Suite         36
Name: count, dtype: int64

In [ ]:
data['property_type'].value_counts()

property_type
Hotel                1107
Resort                197
Homestay              117
Guest House           111
Service Apartment      79
Lodge                  43
Houseboat              39
BnB                    29
Cottage                22
Villa                  16
Bungalow               15
Palace                  7
Farm Stay               5
Motel                   3
Hostel                  1
Tent                    1
Name: count, dtype: int64

In [ ]:
def map(x):
  x =str(x).lower()
  if any(i in x for i in ['farm stay','motel','hostel','tent']):
    return 'Bnb'
  else:
    return x.title()

data['property_type'] = data['property_type'].apply(map)

In [ ]:
data['property_type'].value_counts().index

Index(['Hotel', 'Resort', 'Homestay', 'Guest House', 'Service Apartment',
       'Lodge', 'Bnb', 'Houseboat', 'Cottage', 'Villa', 'Bungalow', 'Palace'],
      dtype='object', name='property_type')

In [ ]:
#creating a random price column based on roomtype
def price_gen(property_type,room_type):
  base = {
      'Hotel':3500,
      'Resort':6000,
      'Homestay':2800,
      'Guest House':2500,
      'Service Apartment':3000,
      'Lodge':1500,
      'Bnb':2000,
      'Houseboat':4000,
      'Cottage':4500,
      'Villa':8000,
      'Bungalow':10000,
      'Palace':15000
  }

  extra = {
      'Standard': 0,
      'Deluxe': 300,
      'Superior': 500,
      'Executive': 750,
      'Suite': 1500,
      'Luxury': 1000
  }

  base_price = base.get(property_type,3000)
  room_charges = extra.get(room_type,1000)
  noise = np.random.randint(-500,2000)
  final_price = base_price + room_charges + noise
  return final_price

In [ ]:
data['price'] = data.apply(
    lambda x: price_gen(x['property_type'],
                        x['room_type_cleaned']),axis=1)

In [ ]:
data.head()

                                      additional_info  ... price
0   Room Service|Internet Access|Restaurant|Free I...  ...  7065
2                            Restaurant|Swimming Pool  ...  6040
3                                       not available  ...  6196
9                                       not available  ...  3662
11         Room Service|Internet Access|Free Internet  ...  4569

[5 rows x 15 columns]

In [ ]:
data['hotel_features'] = (data['property_name'] + ' ' + data['property_type'] +' '+ data['room_type_cleaned'] +
                          ' ' + data['room_facilities'] + " " + data['hotel_star_rating'].fillna('').astype(str) + " "+ data['hotel_category'] +
                          ' '+ data['hotel_facilities'] + ' ' + data['hotel_description'] + ' '+ data['additional_info'])

In [ ]:
data.head()

                                      additional_info  ...                                     hotel_features
0   Room Service|Internet Access|Restaurant|Free I...  ...  Baragarh Regency Resort Deluxe Room Service |B...
2                            Restaurant|Swimming Pool  ...  Bevvan Resort Resort Standard Room Service |Ai...
3                                       not available  ...  Apple Inn Cottage Cottage Deluxe Basic Bathroo...
9                                       not available  ...  Arjun Homestay Homestay Deluxe Room Service |B...
11         Room Service|Internet Access|Free Internet  ...  Apna Ghar- Sector 46 Guest House Deluxe Air Co...

[5 rows x 16 columns]

In [ ]:
data.isnull().sum()

additional_info      0
address              0
city                 0
hotel_category       0
hotel_description    0
hotel_facilities     0
hotel_star_rating    0
point_of_interest    0
property_name        0
property_type        0
room_facilities      0
room_type            0
uniq_id              0
room_type_cleaned    0
price                0
hotel_features       0
dtype: int64

In [ ]:
import joblib
joblib.dump(data,'/content/drive/MyDrive/M7/preprocessed_goibibo')

['/content/drive/MyDrive/M7/preprocessed_goibibo']

# **RELOADING DATA**

In [ ]:
data = joblib.load('/content/drive/MyDrive/M7/preprocessed_goibibo')

In [ ]:
data.head()

                                      additional_info  ...                                     hotel_features
0   Room Service|Internet Access|Restaurant|Free I...  ...  Baragarh Regency Resort Deluxe Room Service |B...
2                            Restaurant|Swimming Pool  ...  Bevvan Resort Resort Standard Room Service |Ai...
3                                       not available  ...  Apple Inn Cottage Cottage Deluxe Basic Bathroo...
9                                       not available  ...  Arjun Homestay Homestay Deluxe Room Service |B...
11         Room Service|Internet Access|Free Internet  ...  Apna Ghar- Sector 46 Guest House Deluxe Air Co...

[5 rows x 16 columns]

In [ ]:
data = data.reset_index(drop=True)

In [ ]:
data.head()

                                     additional_info  ...                                     hotel_features
0  Room Service|Internet Access|Restaurant|Free I...  ...  Baragarh Regency Resort Deluxe Room Service |B...
1                           Restaurant|Swimming Pool  ...  Bevvan Resort Resort Standard Room Service |Ai...
2                                      not available  ...  Apple Inn Cottage Cottage Deluxe Basic Bathroo...
3                                      not available  ...  Arjun Homestay Homestay Deluxe Room Service |B...
4         Room Service|Internet Access|Free Internet  ...  Apna Ghar- Sector 46 Guest House Deluxe Air Co...

[5 rows x 16 columns]

In [ ]:
##using TFIDF
tfidf = TfidfVectorizer(stop_words='english')
tf_matrix = tfidf.fit_transform(data['hotel_features'])

In [ ]:
tf_matrix.data

array([0.16015147, 0.10386505, 0.06334335, ..., 0.10930495, 0.30214424,
       0.24548808])

In [ ]:
##calculating similarity
cs_matrix = cosine_similarity(tf_matrix)

In [ ]:
cs_matrix

array([[1.        , 0.25225293, 0.26085728, ..., 0.36848827, 0.40251603,
        0.22664432],
       [0.25225293, 1.        , 0.20465188, ..., 0.2339254 , 0.27753901,
        0.25154475],
       [0.26085728, 0.20465188, 1.        , ..., 0.34640608, 0.28054542,
        0.25579198],
       ...,
       [0.36848827, 0.2339254 , 0.34640608, ..., 1.        , 0.4508654 ,
        0.31867652],
       [0.40251603, 0.27753901, 0.28054542, ..., 0.4508654 , 1.        ,
        0.3795247 ],
       [0.22664432, 0.25154475, 0.25579198, ..., 0.31867652, 0.3795247 ,
        1.        ]])

In [ ]:
import warnings
warnings.filterwarnings('ignore')

##user input
def reccomend(city,property_type,room_type,star_rating,budget):
  filter_data = data[
      (data['city']==city)&
      (data['property_type']==property_type) &
      (data['room_type_cleaned']==room_type)&
      (data['price']<=budget)&
      (data['hotel_star_rating']>=star_rating)
  ]
  if filter_data.empty:
    return "no hotels found"

  indices = filter_data.index

  query = f"""{city} {property_type} {room_type} {budget} {star_rating} star hotel """

   ##query vector
  query_vector = tfidf.transform([query])

  ##finding simmilarity btwn query vector and selected hotels
  similarity_score = cosine_similarity(query_vector, tf_matrix[indices])

  ##adding similarity scores to the filtered data
  filter_data['similarity_score'] = similarity_score.flatten()
  filter_data = filter_data.drop(['uniq_id','room_type'],axis=1)

  ##top hotels recommended
  recommended = filter_data.sort_values(by= 'similarity_score', ascending=False)

  print("similarity scores: ", similarity_score)

  print("TOP REOMMENDED HOTELS ")
  return recommended.head(10)

In [ ]:
reccomend('Goa','Resort','Deluxe',3,7000)

similarity scores:  [[0.08611612 0.03708585 0.07771293]]
TOP REOMMENDED HOTELS

                                        additional_info  ... similarity_score
403                            Restaurant|Swimming Pool  ...         0.086116
1154  Room Service|Internet Access|Gym/Spa|Swimming ...  ...         0.077713
621             Room Service|Internet Access|Restaurant  ...         0.037086

[3 rows x 15 columns]

In [ ]:
joblib.dump(tfidf,'/content/drive/MyDrive/M7/tfidf')
joblib.dump(tf_matrix,'/content/drive/MyDrive/M7/tfidf_matrix')

['/content/drive/MyDrive/M7/tfidf_matrix']

In [ ]:

!pip install pyngrok

Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.1.2

In [ ]:
from pyngrok import ngrok

!ngrok config add-authtoken 3E4yNTQuD9JKHUcjppGyCx7QQVN_6gD2GK25LhbjDNDkXYZk6

Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml

In [ ]:
#creating flask app
import joblib
from flask import Flask,render_template,request


##loading files
data = joblib.load('/content/drive/MyDrive/M7/preprocessed_goibibo')
data = data.reset_index(drop=True)
tfidf = joblib.load('/content/drive/MyDrive/M7/tfidf')
tfidf_matrix = joblib.load('/content/drive/MyDrive/M7/tfidf_matrix')

##recomendations system
def reccomend1(city,property_type,room_type,star_rating,budget):
  filter_data = data[
      (data['city']==city)&
      (data['property_type']==property_type) &
      (data['price']<=budget)
  ].copy()

  if room_type:
    room_filter = filter_data[filter_data['room_type_cleaned']==room_type]

    if not room_filter.empty:
      filter_data = room_filter

  if star_rating:
    star_filter = filter_data[filter_data['hotel_star_rating']>=star_rating]

    if not star_filter.empty:
      filter_data = star_filter


  if filter_data.empty:
    return pd.DataFrame()

  indices = filter_data.index

  query = f"""{city} {property_type} {room_type} {budget} {star_rating} star hotel """

   ##query vector
  query_vector = tfidf.transform([query])

  ##finding simmilarity btwn query vector and selected hotels
  similarity_score = cosine_similarity(query_vector, tfidf_matrix[indices])

  ##adding similarity scores to the filtered data
  filter_data['similarity_score'] = similarity_score.flatten()
  filter_data = filter_data.drop(['uniq_id','room_type'],axis=1)

  ##top hotels recommended
  recommended = filter_data.sort_values(by='similarity_score', ascending=False)

  print("similarity scores: ", similarity_score)

  print("TOP REOMMENDED HOTELS ")
  print(f"Found {len(recommended)} matching hotels")
  return recommended.head(10)

In [ ]:
from flask import Flask, request, jsonify, render_template_string
from pyngrok import ngrok

app = Flask(__name__)

# =========================
# SAMPLE DROPDOWN VALUES
# =========================

input_row = 100

sample_hotel = data.iloc[input_row]

cities = sorted(
  data['city']
  .dropna()
  .unique()
  )

property_types = sorted(
  data['property_type']
  .dropna()
  .unique())

room_types = sorted(
  data['room_type_cleaned']
  .dropna()
  .unique())

star_ratings = sorted(
  data['hotel_star_rating']
  .dropna()
  .unique()
  )

default_city = sample_hotel['city']

default_property = sample_hotel['property_type']

default_room = sample_hotel['room_type_cleaned']

default_rating = sample_hotel['hotel_star_rating']

default_budget = sample_hotel['price']

In [ ]:
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Hotel Recommendation System</title>

    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', sans-serif;
            min-height: 100vh;
            background:
                linear-gradient(rgba(15, 23, 42, 0.62), rgba(15, 23, 42, 0.72)),
                url('https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=80');
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
            padding: 32px;
            color: #111827;
        }

        .hero {
            max-width: 900px;
            margin: 0 auto 30px;
            text-align: center;
            color: white;
        }

        .hero h1 {
            font-size: 44px;
            font-weight: 800;
            margin-bottom: 10px;
        }

        .hero p {
            font-size: 18px;
            opacity: 0.95;
        }

        .form-container,
        #recommendations {
            max-width: 1200px;
            margin: auto;
        }

        .form-container {
            background: rgba(255, 255, 255, 0.97);
            padding: 34px;
            border-radius: 22px;
            box-shadow: 0 24px 70px rgba(0, 0, 0, 0.22);
        }

        .form-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
            gap: 20px;
        }

        .input-group {
            display: flex;
            flex-direction: column;
        }

        label {
            font-weight: 700;
            margin-bottom: 8px;
            color: #374151;
        }

        select,
        input {
            width: 100%;
            padding: 14px 15px;
            border-radius: 12px;
            border: 1px solid #d1d5db;
            font-size: 15px;
            background: white;
        }

        select:focus,
        input:focus {
            outline: none;
            border-color: #2563eb;
            box-shadow: 0 0 0 4px rgba(37, 99, 235, 0.14);
        }

        button {
            width: 100%;
            margin-top: 26px;
            padding: 17px;
            border: none;
            border-radius: 14px;
            background: linear-gradient(135deg, #2563eb, #059669);
            color: white;
            font-size: 18px;
            font-weight: 800;
            cursor: pointer;
            transition: 0.25s ease;
        }

        button:hover {
            transform: translateY(-2px);
            box-shadow: 0 14px 30px rgba(37, 99, 235, 0.32);
        }

        .loading {
            margin-top: 28px;
            text-align: center;
            color: white;
            font-size: 24px;
            font-weight: 800;
            padding: 36px;
        }

        .hotel-card {
            background: rgba(255, 255, 255, 0.97);
            margin-top: 28px;
            border-radius: 20px;
            padding: 26px;
            box-shadow: 0 16px 42px rgba(0, 0, 0, 0.16);
        }

        .hotel-banner {
            display: inline-block;
            background: #059669;
            color: white;
            padding: 8px 15px;
            border-radius: 999px;
            font-size: 13px;
            font-weight: 800;
            margin-bottom: 16px;
        }

        .hotel-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            gap: 18px;
            flex-wrap: wrap;
        }

        .hotel-name {
            font-size: 28px;
            font-weight: 800;
        }

        .hotel-location {
            color: #6b7280;
            margin-top: 6px;
        }

        .price-box {
            background: #059669;
            color: white;
            padding: 13px 22px;
            border-radius: 14px;
            font-size: 23px;
            font-weight: 800;
            text-align: center;
            min-width: 130px;
        }

        .price-night {
            font-size: 12px;
            font-weight: 600;
        }

        .hotel-tags {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
            margin-top: 22px;
        }

        .hotel-tags span {
            background: #eff6ff;
            color: #1d4ed8;
            padding: 8px 14px;
            border-radius: 999px;
            font-size: 14px;
            font-weight: 700;
        }

        .similarity-score {
            margin-top: 18px;
            padding: 13px;
            background: #ecfdf5;
            color: #047857;
            border-radius: 12px;
            font-weight: 800;
        }

        .details-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
            gap: 18px;
            margin-top: 24px;
        }

        .detail-card {
            background: #f8fafc;
            border: 1px solid #e5e7eb;
            border-radius: 16px;
            padding: 18px;
        }

        .detail-card h3 {
            margin-bottom: 10px;
            font-size: 17px;
        }

        .detail-card p {
            color: #4b5563;
            line-height: 1.5;
            font-size: 14px;
        }

        .no-results {
            background: white;
            border-radius: 20px;
            padding: 42px;
            margin-top: 30px;
            text-align: center;
            box-shadow: 0 16px 42px rgba(0, 0, 0, 0.14);
        }

        @media (max-width: 768px) {
            body {
                padding: 20px;
            }

            .hero h1 {
                font-size: 32px;
            }

            .form-container {
                padding: 24px;
            }

            .price-box {
                width: 100%;
            }
        }
    </style>
</head>

<body>

    <section class="hero">
        <h1>AI Hotel Recommendation System</h1>
        <p>Find the best hotels using smart machine learning recommendations</p>
    </section>

    <main>
        <section class="form-container">
            <form id="recommendForm">

                <div class="form-grid">

                    <div class="input-group">
                        <label for="city">City</label>
                        <select id="city" name="city">
                            {% for city in cities %}
                            <option value="{{ city }}" {% if city == default_city %}selected{% endif %}>
                                {{ city }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="input-group">
                        <label for="property_type">Property Type</label>
                        <select id="property_type" name="property_type">
                            {% for property in property_types %}
                            <option value="{{ property }}" {% if property == default_property %}selected{% endif %}>
                                {{ property }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="input-group">
                        <label for="room_type">Room Type</label>
                        <select id="room_type" name="room_type">
                            {% for room in room_types %}
                            <option value="{{ room }}" {% if room == default_room %}selected{% endif %}>
                                {{ room }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="input-group">
                        <label for="star_rating">Star Rating</label>
                        <select id="star_rating" name="star_rating">
                            {% for rating in star_ratings %}
                            <option value="{{ rating }}" {% if rating == default_rating %}selected{% endif %}>
                                {{ rating }} Star
                            </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="input-group">
                        <label for="budget">Budget Per Night</label>
                        <input
                            id="budget"
                            type="number"
                            name="budget"
                            value="{{ default_budget }}"
                            min="0">
                    </div>

                </div>

                <button type="submit">Search Hotels</button>

            </form>
        </section>

        <section id="recommendations"></section>
    </main>

    <script>
        function fillDropdown(dropdownId, values, selectedValue = "") {
            const dropdown = document.getElementById(dropdownId);
            dropdown.innerHTML = "";

            values.forEach(value => {
                const option = document.createElement("option");
                option.value = value;
                option.textContent = value;

                if (String(value) === String(selectedValue)) {
                    option.selected = true;
                }

                dropdown.appendChild(option);
            });
        }

        async function updateOptions(changedField) {
            const city = document.getElementById("city").value;
            const propertyType = document.getElementById("property_type").value;
            const roomType = document.getElementById("room_type").value;

            const payload = {
                city: city,
                property_type: changedField === "city" ? "" : propertyType,
                room_type: changedField === "city" || changedField === "property_type" ? "" : roomType
            };

            const response = await fetch("/get_options", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify(payload)
            });

            const result = await response.json();

            if (changedField === "city") {
                fillDropdown("property_type", result.property_types || []);
                fillDropdown("room_type", result.room_types || []);
            }

            if (changedField === "property_type") {
                fillDropdown("room_type", result.room_types || []);
            }

            fillDropdown("star_rating", result.star_ratings || []);

            if (result.max_budget && result.max_budget > 0) {
                document.getElementById("budget").max = result.max_budget;
                document.getElementById("budget").placeholder =
                    "Budget between ₹" + result.min_budget + " and ₹" + result.max_budget;
            }
        }

        document.addEventListener("DOMContentLoaded", function () {
            document.getElementById("city").addEventListener("change", function () {
                updateOptions("city");
            });

            document.getElementById("property_type").addEventListener("change", function () {
                updateOptions("property_type");
            });

            document.getElementById("room_type").addEventListener("change", function () {
                updateOptions("room_type");
            });

            document.getElementById("recommendForm").addEventListener("submit", async function(e) {
                e.preventDefault();

                document.getElementById("recommendations").innerHTML = `
                    <div class="loading">
                        Finding the best hotels for you...
                    </div>
                `;

                const formData = new FormData(this);

                const response = await fetch("/recommend", {
                    method: "POST",
                    body: formData
                });

                const data = await response.json();

                let html = "";

                if (data.length === 0) {
                    html = `
                        <div class="no-results">
                            <h2>No Hotels Found</h2>
                            <p>Try increasing budget, changing room type, or reducing star rating.</p>
                        </div>
                    `;
                } else {
                    data.forEach(hotel => {
                        html += `
                            <div class="hotel-card">
                                <div class="hotel-banner">Recommended</div>

                                <div class="hotel-header">
                                    <div>
                                        <div class="hotel-name">${hotel.property_name}</div>
                                        <div class="hotel-location">${hotel.city}</div>
                                    </div>

                                    <div class="price-box">
                                        ₹ ${hotel.price}
                                        <br>
                                        <span class="price-night">per night</span>
                                    </div>
                                </div>

                                <div class="hotel-tags">
                                    <span>${hotel.property_type}</span>
                                    <span>${hotel.room_type_cleaned}</span>
                                    <span>${hotel.hotel_star_rating} Star</span>
                                </div>

                                <div class="similarity-score">
                                    Match Score: ${(hotel.similarity_score * 100).toFixed(1)}%
                                </div>

                                <div class="details-grid">
                                    <div class="detail-card">
                                        <h3>Address</h3>
                                        <p>${hotel.address}</p>
                                    </div>

                                    <div class="detail-card">
                                        <h3>Facilities</h3>
                                        <p>${hotel.hotel_facilities}</p>
                                    </div>

                                    <div class="detail-card">
                                        <h3>Nearby Attractions</h3>
                                        <p>${hotel.point_of_interest}</p>
                                    </div>
                                </div>
                            </div>
                        `;
                    });
                }

                document.getElementById("recommendations").innerHTML = html;
            });
        });
    </script>

</body>
</html>
"""

In [ ]:
@app.route('/')

def home():

  return render_template_string(
      HTML_TEMPLATE,

      cities=cities,

      property_types=property_types,

      room_types=room_types,

      star_ratings=star_ratings,

      default_city=default_city,

      default_property=default_property,

      default_room=default_room,

      default_rating=default_rating,

      default_budget=default_budget

  )


# =========================
# RECOMMEND API
# =========================

@app.route('/get_options', methods=['POST'])
def get_options():

    payload = request.get_json() or {}

    city = payload.get('city')
    property_type = payload.get('property_type')
    room_type = payload.get("room_type")

    filtered = data.copy()

    if city:
        filtered = filtered[filtered["city"] == city]

    if property_type:
        filtered = filtered[filtered["property_type"] == property_type]

    if room_type:
        filtered = filtered[filtered["room_type_cleaned"] == room_type]

    property_types_result = sorted(
        filtered["property_type"].dropna().unique().tolist()
    )

    room_types_result = sorted(
        filtered["room_type_cleaned"].dropna().unique().tolist()
    )

    star_ratings_result = sorted(
        filtered["hotel_star_rating"].dropna().unique().tolist()
    )

    return jsonify({
        "property_types": property_types_result,
        "room_types": room_types_result,
        "star_ratings": star_ratings_result,
        "max_budget": int(filtered["price"].max()) if not filtered.empty else 0,
        "min_budget": int(filtered["price"].min()) if not filtered.empty else 0
    })


@app.route('/recommend', methods=['POST'])

def index():
  city = request.form.get('city')

  property_type = request.form.get('property_type')

  room_type = request.form.get('room_type')

  star_rating = int(request.form.get('star_rating',0))

  budget = int(request.form.get('budget',0))

  recommendations = reccomend1(city,property_type,room_type,star_rating,budget)

  if recommendations.empty:
    return jsonify([])

  cols = ['property_name','city','property_type', 'room_type_cleaned','hotel_star_rating', 'hotel_facilities', 'address', 'point_of_interest', 'price','similarity_score']

  recommendations = recommendations[cols]
  result = recommendations.to_dict( orient='records' )
  print(result)

  return jsonify(result)



# =========================
# NGROK
# =========================

ngrok.kill()
public_url = ngrok.connect(5000)

print("Public URL:", public_url)


# =========================
# RUN APP
# =========================

if __name__ == '__main__':
  app.run(port=5000)

Public URL: NgrokTunnel: "https://vanquish-smile-ellipse.ngrok-free.dev" -> "http://localhost:5000"
 * Serving Flask app '__main__'
 * Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:01:30] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:01:33] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:02:09] "POST /recommend HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:02:22] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.07852911]]
TOP REOMMENDED HOTELS
Found 1 matching hotels
[{'property_name': 'HOTEL SARLA PARADISE', 'city': 'Pilani', 'property_type': 'Hotel', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 0, 'hotel_facilities': 'Internet Access - Surcharge|Parking Facilities Available|Power Backup|Room Service (24 Hours)|Outdoor Parking - Secured|Parking Facility|Room Service', 'address': 'Ward no-14, Ganga Colony, Opposite Utsav Maidan', 'point_of_interest': 'Bus Stand Area', 'price': 4796, 'similarity_score': 0.07852911055819746}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:02:48] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:02:57] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.13881426]]
TOP REOMMENDED HOTELS
Found 1 matching hotels
[{'property_name': 'Sri Sai Sampath Hospitalities', 'city': 'Visakhapatnam', 'property_type': 'Guest House', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 0, 'hotel_facilities': 'Parking Facilities Available|Power Backup|Transfers Available|Internet Access Free|Room Service (24 Hours)|Parking Facility', 'address': 'Near Delicacies Restaurant, MVP Colony, Visakhapatnam', 'point_of_interest': 'Indira Gandhi Zoological Park|Others', 'price': 3404, 'similarity_score': 0.13881426425910331}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:03:10] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.10246754]]
TOP REOMMENDED HOTELS
Found 1 matching hotels
[{'property_name': 'Sri Sai Sampath Hospitalities', 'city': 'Visakhapatnam', 'property_type': 'Guest House', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 0, 'hotel_facilities': 'Parking Facilities Available|Power Backup|Transfers Available|Internet Access Free|Room Service (24 Hours)|Parking Facility', 'address': 'Near Delicacies Restaurant, MVP Colony, Visakhapatnam', 'point_of_interest': 'Indira Gandhi Zoological Park|Others', 'price': 3404, 'similarity_score': 0.10246754409522282}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:03:22] "POST /get_options HTTP/1.1" 200 -
ERROR:__main__:Exception on /recommend [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_1298/66536422.py", line 85, in index
    budget = int(request.form.get('budget',0))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:03:28] "POST /recommend HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:03:37] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.17438345]]
TOP REOMMENDED HOTELS
Found 1 matching hotels
[{'property_name': 'Vizag Palms', 'city': 'Visakhapatnam', 'property_type': 'Guest House', 'room_type_cleaned': 'Executive', 'hotel_star_rating': 0, 'hotel_facilities': 'not available', 'address': 'Plot No.77, SOS Nagar,  Bheemili Village', 'point_of_interest': 'Beach Area', 'price': 4114, 'similarity_score': 0.17438345458551907}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:03:51] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:03:52] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.13715984 0.12527779]]
TOP REOMMENDED HOTELS
Found 2 matching hotels
[{'property_name': 'Sri Sai Sampath Hospitalities', 'city': 'Visakhapatnam', 'property_type': 'Guest House', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 0, 'hotel_facilities': 'Parking Facilities Available|Power Backup|Transfers Available|Internet Access Free|Room Service (24 Hours)|Parking Facility', 'address': 'Near Delicacies Restaurant, MVP Colony, Visakhapatnam', 'point_of_interest': 'Indira Gandhi Zoological Park|Others', 'price': 3404, 'similarity_score': 0.1371598387374064}, {'property_name': 'Vizag Palms', 'city': 'Visakhapatnam', 'property_type': 'Guest House', 'room_type_cleaned': 'Executive', 'hotel_star_rating': 0, 'hotel_facilities': 'not available', 'address': 'Plot No.77, SOS Nagar,  Bheemili Village', 'point_of_interest': 'Beach Area', 'price': 4114, 'similarity_score': 0.1252777923985308}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:03:58] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:04:01] "POST /recommend HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:04:09] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.07442176 0.03689829 0.04784872]]
TOP REOMMENDED HOTELS
Found 3 matching hotels
[{'property_name': 'Hotel Pydhi Grand', 'city': 'Visakhapatnam', 'property_type': 'Hotel', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 2, 'hotel_facilities': 'Doctor on Call|Parking Facilities Available|Medical Assistance Available|Parking Facility|Room Service', 'address': 'DNO - 31-32-46,opp JYOTHI THEATER LADIES GATE , DABAGARDEN,Visakhapatnam (Vizag), A P,India', 'point_of_interest': 'Daba Garden|Matsyadarshini Aquarium|Gajuwaka Bus Depot|Visakhapatnam Airport', 'price': 4863, 'similarity_score': 0.07442176185904271}, {'property_name': 'The Supreme', 'city': 'Visakhapatnam', 'property_type': 'Hotel', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 3, 'hotel_facilities': 'Airport Transfer Available / Surcharge|Business Center |Doctor on Call|Health Club / Gym Facility Available|Internet Access - Surcharge|Laundry Service Available|Lift / Elevator|Lobby|Parking Facilities Available|Front Desk|Multi Cuisine Restaurant |Locker Facility|Local Tour / Travel Desk|Doorman|Air-Conditioning - Central|Power Backup|Express Check-In / Check-Out|Gardens|Air / Rail Booking|Internet / Fax (Reception area only)|Outdoor Parking - Secured|Room Service|Public Restrooms', 'address': 'Beach Road, Collector Office Down, Near Coastal Battery (MAHARANIPETA)', 'point_of_interest': 'Araku Valley|Dolphin Nose|Bheemli Beach|Simhachalam|Rk Beach|Visakhapatnam Railway Station', 'price': 4615, 'similarity_score': 0.047848722212847285}, {'property_name': 'Vaibhav Inn', 'city': 'Visakhapatnam', 'property_type': 'Hotel', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 2, 'hotel_facilities': 'Airport Transfer Available / Surcharge|Doctor on Call|Laundry Service Available|Lift / Elevator|Lobby|Parking Facilities Available|Front Desk|24 Hour Front Desk|Power Backup|Electronic / Magnetic Keys|Car Rental|Taxi Services|Internet Access Free|Newspapers In Lobby|Electronic Check-Out|Room Service (24 Hours)|STD / ISD|Internet / Fax (Reception area only)|Parking Facility', 'address': '30-12-34,Ranga street, Beside Nellore Mess, Dabagardens,', 'point_of_interest': 'Araku Valley|Ramakrishna Beach|Simhachalam|Dwaraka Bus stand|Daba Garden|Visakhapatnam Railway Station', 'price': 4524, 'similarity_score': 0.036898287146882376}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:04:42] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:05:02] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.16195933]]
TOP REOMMENDED HOTELS
Found 1 matching hotels
[{'property_name': 'SHYAM INN(LODGE)', 'city': 'Visakhapatnam', 'property_type': 'Lodge', 'room_type_cleaned': 'Standard', 'hotel_star_rating': 0, 'hotel_facilities': 'Airport Transfer Available / Surcharge|Babysitting/ Child Care (surcharge)|Ballroom|Barbecue Area|Internet Access - Surcharge|Lobby|Night Club|Front Desk|Luggage Storage|Doorman|Multi Lingual Staff|Exhibit Space|Fitness Equipment|Suitable For Children|Veranda|Open Air Restaurant / Dining |Transfers Available| Bike on Rent|Fun Floats', 'address': 'SRIKANYA ROAD RAILWAY NEW COLONY', 'point_of_interest': 'Visakhapatnam Railway Station|Others|Visakhapatnam Airport', 'price': 3345, 'similarity_score': 0.16195933363235637}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:05:17] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:05:28] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.13935625]]
TOP REOMMENDED HOTELS
Found 1 matching hotels
[{'property_name': 'Vishnu Lodge', 'city': 'Warangal', 'property_type': 'Lodge', 'room_type_cleaned': 'Standard', 'hotel_star_rating': 1, 'hotel_facilities': 'Doctor on Call|Front Desk|Parking Facility|Room Service', 'address': 'Station Rd, Sri Krishna Colony, Girmajipet, Warangal, Telangana 506002', 'point_of_interest': 'Station Road', 'price': 2252, 'similarity_score': 0.1393562536376176}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:06:01] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:06:04] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:06:22] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.13205368]]
TOP REOMMENDED HOTELS
Found 1 matching hotels
[{'property_name': 'D Lake View Resort', 'city': 'Hyderabad', 'property_type': 'Resort', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 0, 'hotel_facilities': 'not available', 'address': 'Survey No. 13P Chilkuri Balaji Temple Road Aziz Nagar Village Moinabad, Hyderabad  Telangana,', 'point_of_interest': 'Hyderabad Deccan Railway Station|NTR Garden|Secretariat|Hyderabad Central|Birla Mandir|Hussain Sagar|GVK ONE|Ravindra Bharti|Lumbini Park|MPM Mall|Others|Nampally Railway Station|Paradise', 'price': 7348, 'similarity_score': 0.13205368396817665}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:06:34] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:06:34] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.06559241 0.11796818]]
TOP REOMMENDED HOTELS
Found 2 matching hotels
[{'property_name': 'Vista Homes 3 - Gachibowli', 'city': 'Hyderabad', 'property_type': 'Service Apartment', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 0, 'hotel_facilities': 'Doctor on Call|Lobby|Parking Facilities Available|Front Desk|Internet Access Free|Room Service (24 Hours)|RO Water Purification System', 'address': 'E-14, Rolling Hills,Gachibowli', 'point_of_interest': 'Cathedral Church of The Redemption|Gurudwara Rakabganj Sahib|French Cultural Center in India|Embassy Of Ireland|Vigyan Bhawan|Dr. Ram Manohar Lohia Hospital|Major Dhyan Chand National Stadium|High Commision of Pakistan|Parliament House|Khan Market|Talkatora Indoor Stadium|Gurudwara Bangla Sahib|Embassy of Portugal|India Gate|German Embassy|Embassy of Spain|Rashtrapati Bhawan|Embassy of Georgia|Old Fort|Talkatora Stadium|Embassy of Israel|Vietnam Embassy|High Commission of Sri Lanka|Banjara Hills Area|C.S.I.R. - Council Of Scientific and Industrial Research|Delhi Zoo|Brazil Embassy|Mughal Garden', 'price': 3079, 'similarity_score': 0.11796818316920737}, {'property_name': 'Vista Homes 1- Jubilee Hills', 'city': 'Hyderabad', 'property_type': 'Service Apartment', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 0, 'hotel_facilities': 'Doctor on Call|Lobby|Front Desk|RO Water Purification System', 'address': 'Plot No.1278, Suvarna Nilayam,Jubilee Hills Check post,Land Mark : Bharath Petrol pump.', 'point_of_interest': 'details Unavailable', 'price': 3572, 'similarity_score': 0.06559241104059538}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:07:23] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:07:30] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.22236113]]
TOP REOMMENDED HOTELS
Found 1 matching hotels
[{'property_name': 'Athidhi Guest House', 'city': 'Hyderabad', 'property_type': 'Guest House', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 0, 'hotel_facilities': 'Laundry Service Available|Medical Assistance Available|Suitable For Children|Room Service', 'address': 'Flat no 308,Block 2,Sarada Apartments II, Next lane to Axis Bank, Road No.1, Banjara Hills', 'point_of_interest': 'Banjara Hills Area', 'price': 3379, 'similarity_score': 0.2223611258940817}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:07:45] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:07:57] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:08:00] "POST /recommend HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:08:05] "POST /recommend HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:08:19] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.06516262]]
TOP REOMMENDED HOTELS
Found 1 matching hotels
[{'property_name': 'Tivoli Grand Resort Hotel', 'city': 'Delhi', 'property_type': 'Resort', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 3, 'hotel_facilities': 'Swimming Pool|Babysitting/ Child Care (surcharge)|Banquet Facilities|Business Center |Currency Exchange|Doctor on Call|Dry Cleaning|Internet Access - Surcharge|Laundry Service Available|Lobby|Parking Facilities Available|Front Desk|Multi Cuisine Restaurant |Locker Facility|Local Tour / Travel Desk|Major Credit Cards Accepted|24 Hour Front Desk|Medical Assistance Available|Welcome Drinks|Power Backup|Gardens|Audio - Visual Equipment|Wedding Services Facility|Wake-up Call / Service|Conference Facility |Limousine Service Available|Wheelchair Accessibility - Room|Car Rental|Taxi Services|Board Room|Newspapers In Lobby|Whirlpool Bath / Shower Cubicle|Room Service (24 Hours)|Party hall|STD / ISD|Adjoining Rooms|RO Water Purification System|Internet Access', 'address': 'Main G.T. Karnal Road, Jindpur', 'point_of_interest': 'Alipur|North Delhi', 'price': 6717, 'similarity_score': 0.06516261800021776}]

INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:08:41] "POST /get_options HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2026 11:08:53] "POST /recommend HTTP/1.1" 200 -

similarity scores:  [[0.1581858]]
TOP REOMMENDED HOTELS
Found 1 matching hotels
[{'property_name': 'Arjun Homestay', 'city': 'Delhi', 'property_type': 'Homestay', 'room_type_cleaned': 'Deluxe', 'hotel_star_rating': 0, 'hotel_facilities': 'Doctor on Call|Front Desk|24 Hour Front Desk', 'address': '51 Amri Nagar south ex', 'point_of_interest': 'Safdarjung Station|Hungary Embassy|Dilli Haat|AIIMS|R. K. Khanna Tennis Stadium|Khan Market|ISKCON Temple|AASHLOK Hospital|Thyagaraj Sports Complex|Japanese Embassy|INA Market|French Cultural Center in India|South Extension|Hauz Khas|Lajpat Nagar Market|Embassy of Spain|Lajpat Nagar|Lodhi Gardens|Metro Station Hauz Khas|Deer Park|Embassy of The Arab Republic of Egypt|Masjid Moth|Hazrat Nizammudin Railway Station|Ethiopia Embassy|Humayuns Tomb|Jawaharlal Nehru Stadium|Moolchand Medcity|Sarojini Nagar Market|Safdarjang Hospital|Embassy of Israel|Siri Fort|Brazil Embassy', 'price': 3662, 'similarity_score': 0.15818580424935838}]

WARNING:pyngrok.process.ngrok:t=2026-05-29T12:48:28+0000 lvl=warn msg="Stopping forwarder" name=http-5000-5b4c83ca-a4bb-4715-bd84-fa9980878475 acceptErr="failed to accept connection: Listener closed"

In [ ]:
HTML_TEMPLATE = """

<!DOCTYPE html>
<html>

<head>

<title>🏨 AI Hotel Recommendation System</title>

<meta name="viewport"
content="width=device-width, initial-scale=1">

<style>

*{
    margin:0;
    padding:0;
    box-sizing:border-box;
}

body{

    font-family:'Segoe UI',sans-serif;

    background:
    linear-gradient(
        135deg,
        #667eea,
        #764ba2
    );

    min-height:100vh;

    padding:40px;
}

.hero{

    text-align:center;

    color:white;

    margin-bottom:30px;
}

.hero h1{

    font-size:42px;

    margin-bottom:10px;
}

.hero p{

    font-size:18px;

    opacity:.9;
}

.form-container{

    background:white;

    max-width:1400px;

    margin:auto;

    padding:35px;

    border-radius:30px;

    box-shadow:
    0 20px 60px
    rgba(0,0,0,.15);
}

.form-grid{

    display:grid;

    grid-template-columns:
    repeat(auto-fit,minmax(250px,1fr));

    gap:20px;
}

.input-group{

    display:flex;

    flex-direction:column;
}

label{

    font-weight:600;

    margin-bottom:8px;

    color:#374151;
}

select,
input{

    padding:15px;

    border-radius:14px;

    border:1px solid #e5e7eb;

    font-size:15px;
}

select:focus,
input:focus{

    outline:none;

    border-color:#6366f1;
}

button{

    width:100%;

    margin-top:25px;

    padding:18px;

    border:none;

    border-radius:16px;

    background:
    linear-gradient(
        135deg,
        #4f46e5,
        #7c3aed
    );

    color:white;

    font-size:18px;

    font-weight:600;

    cursor:pointer;

    transition:.3s;
}

button:hover{

    transform:
    translateY(-2px);

    box-shadow:
    0 12px 25px
    rgba(79,70,229,.35);
}

.loading{

    text-align:center;

    color:white;

    font-size:24px;

    font-weight:bold;

    padding:40px;
}

.hotel-card{

    background:white;

    margin-top:30px;

    border-radius:24px;

    padding:25px;

    box-shadow:
    0 10px 30px
    rgba(0,0,0,.08);

    transition:.3s;
}

.hotel-card:hover{

    transform:
    translateY(-5px);

    box-shadow:
    0 15px 40px
    rgba(0,0,0,.15);
}

.hotel-banner{

    display:inline-block;

    background:#10b981;

    color:white;

    padding:8px 16px;

    border-radius:999px;

    font-size:13px;

    font-weight:bold;

    margin-bottom:15px;
}

.hotel-header{

    display:flex;

    justify-content:space-between;

    align-items:center;

    flex-wrap:wrap;
}

.hotel-name{

    font-size:28px;

    color:#111827;
}

.hotel-location{

    color:#6b7280;

    margin-top:6px;
}

.price-box{

    background:#10b981;

    color:white;

    padding:12px 20px;

    border-radius:14px;

    font-size:22px;

    font-weight:bold;
}

.price-night{

    font-size:12px;
}

.hotel-tags{

    display:flex;

    flex-wrap:wrap;

    gap:10px;

    margin-top:20px;
}

.hotel-tags span{

    background:#eef2ff;

    color:#4338ca;

    padding:8px 15px;

    border-radius:999px;

    font-size:14px;

    font-weight:600;
}

.similarity-score{

    margin-top:18px;

    padding:12px;

    background:#eef2ff;

    color:#4338ca;

    border-radius:12px;

    font-weight:bold;
}

.details-grid{

    display:grid;

    grid-template-columns:
    repeat(auto-fit,minmax(250px,1fr));

    gap:20px;

    margin-top:25px;
}

.detail-card{

    background:#f8fafc;

    border-radius:18px;

    padding:20px;
}

.detail-card h3{

    margin-bottom:10px;
}

.no-results{

    background:white;

    border-radius:24px;

    padding:40px;

    margin-top:30px;

    text-align:center;
}

async function updateCityOptions(){

    const city =
        document.getElementById(
            'city'
        ).value;

    const response =
        await fetch(
            '/get_options',
            {
                method:'POST',

                headers:{
                    'Content-Type':
                    'application/json'
                },

                body:JSON.stringify({
                    city:city
                })
            }
        );

    const result =
        await response.json();

    // PROPERTY TYPES

    const propertyDropdown =
        document.getElementById(
            'property_type'
        );

    propertyDropdown.innerHTML='';

    result.property_types.forEach(item=>{

        propertyDropdown.innerHTML +=
        `
        <option value="${item}">
            ${item}
        </option>
        `;

    });

    // ROOM TYPES

    const roomDropdown =
        document.getElementById(
            'room_type'
        );

    roomDropdown.innerHTML='';

    result.room_types.forEach(item=>{

        roomDropdown.innerHTML +=
        `
        <option value="${item}">
            ${item}
        </option>
        `;

    });

}

</style>

</head>

<body>

<div class="hero">

<h1>🏨 AI Hotel Recommendation System</h1>

<p>Find the best hotels using Machine Learning</p>

</div>

<div class="form-container">

<form id="recommendForm">

<div class="form-grid">

<div class="input-group">
<label>City</label>
<select id="city" name="city">
{% for city in cities %}
<option value="{{ city }}"
{% if city == default_city %}selected{% endif %}>
{{ city }}
</option>
{% endfor %}
</select>
</div>

<div class="input-group">
<label>Property Type</label>
<select id="property_type" name="property_type">
{% for property in property_types %}
<option value="{{ property }}"
{% if property == default_property %}selected{% endif %}>
{{ property }}
</option>
{% endfor %}
</select>
</div>

<div class="input-group">
<label>Room Type</label>
<select id="room_type" name="room_type">
{% for room in room_types %}
<option value="{{ room }}"
{% if room == default_room %}selected{% endif %}>
{{ room }}
</option>
{% endfor %}
</select>
</div>

<div class="input-group">
<label>Star Rating</label>
<select id="star_rating" name="star_rating">
{% for rating in star_ratings %}
<option value="{{ rating }}"
{% if rating == default_rating %}selected{% endif %}>
⭐ {{ rating }} Star
</option>
{% endfor %}
</select>
</div>

<div class="input-group">
<label>Budget</label>
<input
id="budget"
type="number"
name="budget"
value="{{ default_budget }}">
</div>

</div>

<button type="submit">
🔍 Search Hotels
</button>

</form>

</div>

<div id="recommendations"></div>

<script>

document.getElementById(
'recommendForm'
).addEventListener(

'submit',

async function(e){

e.preventDefault();

document.getElementById(
'recommendations'
).innerHTML = `
<div class="loading">
🔍 Finding Best Hotels...
</div>
`;

const formData =
new FormData(this);

const response =
await fetch(
'/recommend',
{
method:'POST',
body:formData
}
);

const data =
await response.json();

console.log(data);

let html='';

if(data.length===0){

html=`
<div class="no-results">

<h2>
😔 No Hotels Found
</h2>

<br>

<p>
Try increasing budget,
changing room type,
or reducing star rating.
</p>

</div>
`;
}

else{

data.forEach(hotel=>{

html += `

<div class="hotel-card">

<div class="hotel-banner">
⭐ Recommended
</div>

<div class="hotel-header">

<div>

<div class="hotel-name">
${hotel.property_name}
</div>

<div class="hotel-location">
📍 ${hotel.city}
</div>

</div>

<div class="price-box">

₹ ${hotel.price}

<br>

<span class="price-night">
per night
</span>

</div>

</div>

<div class="hotel-tags">

<span>
🏨 ${hotel.property_type}
</span>

<span>
🛏 ${hotel.room_type_cleaned}
</span>

<span>
⭐ ${hotel.hotel_star_rating}
</span>

</div>

<div class="similarity-score">

Match Score:
${(hotel.similarity_score*100).toFixed(1)}%

</div>

<div class="details-grid">

<div class="detail-card">

<h3>📍 Address</h3>

<p>
${hotel.address}
</p>

</div>

<div class="detail-card">

<h3>🏨 Facilities</h3>

<p>
${hotel.hotel_facilities}
</p>

</div>

<div class="detail-card">

<h3>🎯 Nearby Attractions</h3>

<p>
${hotel.point_of_interest}
</p>

</div>

</div>

</div>

`;

});

}

document.getElementById(
'recommendations'
).innerHTML = html;

});

window.onload = function(){

    updateCityOptions();

};

</script>

</body>
</html>

"""